smartarm2:
  kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  # kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005